add_newline = false

right_format = "$time"

[nodejs]
format = "[🤖 $version](bold green) "

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[aws]
symbol = '🅰 '
disabled = true
[aws.region_aliases]
ap-northeast-1 = 'jp'

[gcloud]
disabled = true
symbol = '🅶 '
